'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const a=require('../finance/accounting-core.js');
const organization={salaryAccountId:'p',accounts:[{id:'p',name:'BBVA',folders:[]},{id:'r',name:'Revolut',folders:[]}],assignments:{charge:{accountId:'r',folderId:''}}};
const adjustments=(records)=>({'2026-08':{expenseOverrides:{__accountObservedBalances:records}}});
const base={organization,periodYm:'2026-08',asOf:'2026-08-13',potentialNow:100,events:[],futureEvents:[]};
const secondary=a.resolveAccountState({...base,monthAdjustments:adjustments({r:{amount:30,observedAt:'2026-08-13',kind:'account_observed'}})});
assert.equal(secondary.secondary[0].current,30);
assert.equal(secondary.primary.current,100);
assert.equal(secondary.total,130);
const both=a.resolveAccountState({...base,monthAdjustments:adjustments({p:{amount:70,observedAt:'2026-08-13',kind:'account_observed'},r:{amount:30,observedAt:'2026-08-13',kind:'account_observed'}})});
assert.equal(both.primary.current,70);
assert.equal(both.secondary[0].current,30);
assert.equal(both.total,100);
const projected=a.resolveAccountState({...base,futureEvents:[{itemId:'charge',type:'Gasto',amount:-10,date:new Date('2026-08-20T12:00:00')}],monthAdjustments:adjustments({r:{amount:30,observedAt:'2026-08-13',kind:'account_observed'}})});
assert.equal(projected.secondary[0].current,30);
assert.equal(projected.secondary[0].projected,20);
const ui=fs.readFileSync(path.join(__dirname,'..','ui','accounts.js'),'utf8');
assert.ok(ui.includes('C().KEYS.accountBalances'));
assert.ok(ui.includes('accountBalance(b.dataset.updateAccountBalance)'));
assert.equal(ui.includes('openAccountBalanceEditor(b.dataset.updateAccountBalance)'),false);
console.log('account-observed-balance ok');
