'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const version=fs.readFileSync(path.join(root,'version.js'),'utf8');
const bootstrap=fs.readFileSync(path.join(root,'ui','accounts.js'),'utf8');
const summary=fs.readFileSync(path.join(root,'folder-mode-summary-v2.js'),'utf8');
const v3=fs.readFileSync(path.join(root,'folder-mode-enhancements-v3.js'),'utf8');
const v4=fs.readFileSync(path.join(root,'folder-mode-fixes-v4.js'),'utf8');
const v5=fs.readFileSync(path.join(root,'ui-fixes-v5.js'),'utf8');
assert.match(version,/finance\/accounting-core\.js/);assert.match(version,/ui\/accounts\.js/);assert.match(version,/ui\/account-observed-adapter\.js/);
for(const mod of ['folder-mode-summary-v2.js','folder-mode-enhancements-v3.js','folder-mode-fixes-v4.js','ui-fixes-v5.js','account-routing-current.js'])assert.ok(bootstrap.includes(mod),`bootstrap missing ${mod}`);
for(const forbidden of ['accounting-invariants-hotfix.js','account-display-current.js','account-balance-engine-v6.js'])assert.equal(bootstrap.includes(forbidden),false,`legacy monetary runtime loaded: ${forbidden}`);
assert.match(summary,/DineroZaurioAccountingCore/);assert.equal(summary.includes('buildTodayFinancialSnapshot = function patchedBuildTodayFinancialSnapshot'),false);
assert.match(v3,/dzUniversalAdd/);assert.match(v3,/dzForecastRow/);assert.equal(v3.includes('injectRoutingEditor'),false);
assert.match(v4,/dzFolderMini/);assert.match(v4,/DineroZaurioAccountingCore/);
assert.match(v5,/dzV5SettingsPanel/);assert.equal(v5.includes('knownSecondaryBalance'),false);
console.log('runtime-contract ok');
