'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const version=fs.readFileSync(path.join(root,'version.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'ui','accounts.js'),'utf8');
const observed=fs.readFileSync(path.join(root,'ui','account-observed-adapter.js'),'utf8');
assert.match(version,/dz-accounting-loading/);
assert.match(version,/accounts-ui-7/);
assert.equal(/renderHomeDashboard\s*\(/.test(version),false,'loader must not trigger an extra dashboard render');
const build=version.match(/build:\s*"(\d+)"/)?.[1];assert.ok(build,'runtime build');
assert.ok(version.includes(`accounting-core.js?v=${build}`));
assert.ok(version.includes(`accounts.js?v=${build}`));
assert.ok(version.includes(`account-observed-adapter.js?v=${build}`));
assert.match(ui,/const V='accounts-ui-7'/);
assert.match(ui,/base=renderHomeDashboard/);
assert.match(ui,/base\.apply\(this,a\)/);
assert.match(ui,/function draw\(\)/);
assert.equal(ui.includes('renderCanonicalHomeDashboard'),false);
assert.match(observed,/openAccountBalanceEditor=function\(accountId\)/);
assert.match(observed,/core\.KEYS\.accountBalances/);
assert.equal(observed.includes('account.actualBalance='),false);
console.log('baseline-renderer-gate-contract ok');
