'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const bootstrap=fs.readFileSync(path.join(root,'ui','accounts.js'),'utf8');
const summary=fs.readFileSync(path.join(root,'folder-mode-summary-v2.js'),'utf8');
const enhancements=fs.readFileSync(path.join(root,'folder-mode-enhancements-v3.js'),'utf8');
const routing=fs.readFileSync(path.join(root,'account-routing-current.js'),'utf8');
const observed=fs.readFileSync(path.join(root,'ui','account-observed-adapter.js'),'utf8');
for(const file of ['folder-mode-summary-v2.js','folder-mode-enhancements-v3.js','folder-mode-fixes-v4.js','ui-fixes-v5.js','account-routing-current.js']) assert.ok(bootstrap.includes(file),file);
for(const token of ['resolveAccountState','__DINEROZAURIO_ACCOUNT_DIAGNOSTICS__','folderTransfers','generalTransfers']) assert.ok(summary.includes(token),token);
for(const token of ['dzUniversalAdd','__personalLoans','borrowed','lent','Registrar devolución']) assert.ok(enhancements.includes(token),token);
for(const token of ['openSimpleEditor','openDebtEditor','openGoalEditor','saveSimpleBtn','saveDebtBtn','saveGoalBtn','data-dz-current-routing']) assert.ok(routing.includes(token),token);
for(const token of ['resolveAccountState','savingsStage','savingsConfirmations']) assert.ok(observed.includes(token),token);
assert.equal(/readMoney|textContent\.replace|parseFloat\([^\n]*textContent/.test([summary,enhancements,routing,observed].join('\n')),false);
console.log('ui-contract ok');
