import { createExpenseRule, createIncomeRule, createSavingsGoal, createDebt, createAccount, createBucket, effectiveAmountChange, setRuleEnabledFrom } from '../application/configuration-service.js';
import { minorToMajor } from '../core/money.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const major=minor=>Number(minorToMajor(Number(minor||0))).toFixed(2);

export class ConfigurationUi {
  constructor({repository,getState,onChanged,toast}){this.repository=repository;this.getState=getState;this.onChanged=onChanged;this.toast=toast||(()=>{});}
  state(){return this.getState();}
  render(root){
    const s=this.state();if(!s||!root)return;
    root.innerHTML=`
      <div class="configGrid">
        ${this.section('Ingresos',s.incomeRules,'income')}
        ${this.section('Gastos',s.expenseRules,'expense')}
        ${this.section('Deudas',s.debts,'debt')}
        ${this.section('Ahorro',s.savingsGoals,'saving')}
        ${this.accountSection(s)}
        ${this.periodSection(s)}
      </div>`;
    root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>this.add(b.dataset.add));
    root.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>this.changeAmount(b.dataset.change,b.dataset.id));
    root.querySelectorAll('[data-pause]').forEach(b=>b.onclick=()=>this.pause(b.dataset.pause,b.dataset.id));
    root.querySelectorAll('[data-add-bucket]').forEach(b=>b.onclick=()=>this.addBucket(b.dataset.addBucket));
  }
  section(title,items,type){
    return `<article class="card configCard"><div class="sectionHead"><div><span class="eyebrow">CONFIGURACIÓN</span><h2>${esc(title)}</h2></div><button class="primary" data-add="${type}">Añadir</button></div><div class="configRows">${(items||[]).map(item=>this.item(item,type)).join('')||'<p class="muted">Todavía no hay elementos.</p>'}</div></article>`;
  }
  item(item,type){
    const amount=type==='debt'?(this.state().debtSchedules.find(x=>x.debtId===item.id)?.paymentAmountMinor||0):type==='saving'?item.contributionMinor:item.amountMinor;
    const sourceType=type==='expense'?'expense_rule':type==='income'?'income_rule':type==='saving'?'savings_goal':'debt_schedule';
    return `<div class="configRow"><div><strong>${esc(item.name)}</strong><small>${major(amount)} €${item.status?` · ${esc(item.status)}`:''}</small></div><div class="configActions"><button class="ghost" data-change="${sourceType}" data-id="${item.id}">Importe</button>${type!=='debt'?`<button class="ghost" data-pause="${sourceType}" data-id="${item.id}">Pausar</button>`:''}</div></div>`;
  }
  accountSection(s){return`<article class="card configCard"><div class="sectionHead"><div><span class="eyebrow">ESTRUCTURA</span><h2>Cuentas y carpetas</h2></div><button class="primary" data-add="account">Añadir cuenta</button></div>${s.accounts.map(a=>`<div class="configAccount"><div class="configRow"><div><strong>${esc(a.name)}</strong><small>${a.isPrimary?'Principal':'Secundaria'} · ${esc(a.accountType)}</small></div><button class="ghost" data-add-bucket="${a.id}">Añadir carpeta</button></div><div class="configBuckets">${s.buckets.filter(b=>b.accountId===a.id).map(b=>`<span>${esc(b.name)}</span>`).join('')}</div></div>`).join('')}</article>`;}
  periodSection(s){return`<article class="card configCard"><span class="eyebrow">PERIODO</span><h2>Cómo organizas tu mes</h2><p><strong>${s.plan.periodMode==='salary_cycle'?'Sueldo a sueldo':'Mes natural'}</strong></p><p class="muted">${s.plan.salaryFundingStrategy==='funds_next_month'?'La nómina recibida al final del mes financia el periodo siguiente.':'La nómina financia el mismo mes.'}</p><p class="muted">Cambiar esta semántica afecta cómo se agrupan los movimientos, no sus fechas reales.</p></article>`;}
  async add(type){try{if(type==='expense')return await this.addExpense();if(type==='income')return await this.addIncome();if(type==='saving')return await this.addSaving();if(type==='debt')return await this.addDebt();if(type==='account')return await this.addAccount();}catch(error){this.toast(error.message);}}
  accountOptions(includeBucket=false){const s=this.state();const out=[];for(const account of s.accounts){out.push({value:`${account.id}|`,label:`${account.name} · saldo libre`});if(includeBucket)for(const b of s.buckets.filter(x=>x.accountId===account.id))out.push({value:`${account.id}|${b.id}`,label:`${account.name} · ${b.name}`});}return out;}
  async addExpense(){const s=this.state(),name=prompt('Nombre del gasto:');if(!name)return;const amount=prompt('Importe habitual (€):');if(amount===null)return;const startDate=prompt('Fecha del próximo cargo (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!startDate)return;const frequency=prompt('Frecuencia: monthly, weekly, interval_days, interval_months, yearly, one_time','monthly')||'monthly';const intervalValue=['interval_days','interval_months'].includes(frequency)?Number(prompt('Intervalo:',frequency==='interval_days'?'14':'2')||1):1;const choices=this.accountOptions(true);const route=prompt(`Destino (pega el número):\n${choices.map((x,i)=>`${i+1}. ${x.label}`).join('\n')}`,'1');const chosen=choices[Math.max(0,Number(route||1)-1)]||choices[0], [accountId,bucketId='']=String(chosen?.value||'|').split('|');const salaryRelative=confirm('¿Este presupuesto debe ocurrir al cobrar la nómina, en lugar de un día fijo?');await createExpenseRule({repository:this.repository,planId:s.plan.id,name,amount:Number(String(amount).replace(',','.')),accountId:accountId||null,bucketId:bucketId||null,startDate,frequency,intervalValue,calendarRule:'fixed_day',dueDay:Number(startDate.slice(8,10)),fundingRelativeToSalaryId:salaryRelative?s.plan.salarySourceId:null});this.toast('Gasto creado');await this.onChanged();}
  async addIncome(){const s=this.state(),name=prompt('Nombre del ingreso:');if(!name)return;const amount=prompt('Importe (€):');if(amount===null)return;const startDate=prompt('Fecha del próximo ingreso (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!startDate)return;const account=s.accounts.find(a=>a.isPrimary)||s.accounts[0];await createIncomeRule({repository:this.repository,planId:s.plan.id,name,amount:Number(String(amount).replace(',','.')),accountId:account?.id,startDate,frequency:'monthly',calendarRule:'fixed_day',dueDay:Number(startDate.slice(8,10))});this.toast('Ingreso creado');await this.onChanged();}
  async addSaving(){const s=this.state(),name=prompt('Nombre del objetivo de ahorro:');if(!name)return;const target=prompt('Objetivo total (€):','0'),contribution=prompt('Aportación mensual (€):','0'),startDate=prompt('Fecha de primera aportación (AAAA-MM-DD):',new Date().toISOString().slice(0,10));const choices=this.accountOptions(true),route=prompt(`Destino (pega el número):\n${choices.map((x,i)=>`${i+1}. ${x.label}`).join('\n')}`,'1'),chosen=choices[Math.max(0,Number(route||1)-1)]||choices[0],[accountId,bucketId='']=String(chosen?.value||'|').split('|');await createSavingsGoal({repository:this.repository,planId:s.plan.id,name,target:Number(String(target||0).replace(',','.')),contribution:Number(String(contribution||0).replace(',','.')),accountId:accountId||null,bucketId:bucketId||null,startDate,dueDay:Number(startDate.slice(8,10))});this.toast('Objetivo creado');await this.onChanged();}
  async addDebt(){const s=this.state(),name=prompt('Nombre de la deuda:');if(!name)return;const creditor=prompt('Entidad / acreedor:','')||'',principal=prompt('Importe original (€):','0'),balance=prompt('Saldo pendiente actual (€):',principal||'0'),payment=prompt('Cuota (€):','0'),interest=prompt('TIN anual %:','0'),startDate=prompt('Fecha de próxima cuota (AAAA-MM-DD):',new Date().toISOString().slice(0,10)),remaining=prompt('Cuotas restantes (vacío si no se sabe):','');const account=s.accounts.find(a=>a.isPrimary)||s.accounts[0];await createDebt({repository:this.repository,planId:s.plan.id,name,creditor,debtType:'loan',principal:Number(String(principal||0).replace(',','.')),currentBalance:Number(String(balance||0).replace(',','.')),interestRate:Number(String(interest||0).replace(',','.')),accountId:account?.id,startDate,paymentAmount:Number(String(payment||0).replace(',','.')),remainingInstallments:remaining===''?null:Number(remaining),dueDay:Number(startDate.slice(8,10))});this.toast('Deuda creada');await this.onChanged();}
  async addAccount(){const s=this.state(),name=prompt('Nombre de la cuenta:');if(!name)return;const institution=prompt('Banco / institución:','')||'';await createAccount({repository:this.repository,planId:s.plan.id,name,institutionName:institution});this.toast('Cuenta creada');await this.onChanged();}
  async addBucket(accountId){const name=prompt('Nombre de la carpeta:');if(!name)return;await createBucket({repository:this.repository,accountId,name});this.toast('Carpeta creada');await this.onChanged();}
  async changeAmount(sourceType,id){const current=this.lookupAmount(sourceType,id),amount=prompt('Nuevo importe (€):',major(current));if(amount===null)return;const from=prompt('Aplicar desde (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!from)return;await effectiveAmountChange({repository:this.repository,planId:this.state().plan.id,sourceType,sourceId:id,effectiveFrom:from,amount:Number(String(amount).replace(',','.'))});this.toast('Cambio programado sin reescribir el histórico');await this.onChanged();}
  lookupAmount(sourceType,id){const s=this.state();if(sourceType==='expense_rule')return s.expenseRules.find(x=>x.id===id)?.amountMinor||0;if(sourceType==='income_rule')return s.incomeRules.find(x=>x.id===id)?.amountMinor||0;if(sourceType==='savings_goal')return s.savingsGoals.find(x=>x.id===id)?.contributionMinor||0;if(sourceType==='debt_schedule')return s.debtSchedules.find(x=>x.debtId===id)?.paymentAmountMinor||0;return 0;}
  async pause(sourceType,id){const from=prompt('Pausar desde (AAAA-MM-DD):',new Date().toISOString().slice(0,10));if(!from)return;await setRuleEnabledFrom({repository:this.repository,planId:this.state().plan.id,sourceType,sourceId:id,effectiveFrom:from,enabled:false});this.toast('Pausa programada');await this.onChanged();}
}
